CRITICAL BUG FIX Fixed a bug in the mechanism which first try creating a static-contatiner for adapters. The temporary created adapter was keeping a reference in the model, and eventually it was notified even if it was supposed to be no longer existant.
This fixes a row of problems we had in examples and tests, all exiting
with an exception like:

Calling <bound method StaticContainerAdapter._on_prop_changed of <gtkmvc.adapters.containers.StaticContainerAdapter object at 0x97a104c>>
Traceback (most recent call last):
  File "/home/cavada/Projects/pygtkmvc/trunk.157/gtkmvco/gtkmvc/adapters/basic.py", line 313, in _on_wid_changed
    self.update_model()
  File "/home/cavada/Projects/pygtkmvc/trunk.157/gtkmvco/gtkmvc/adapters/basic.py", line 160, in update_model
    self._write_property(self._read_widget())
  File "/home/cavada/Projects/pygtkmvc/trunk.157/gtkmvco/gtkmvc/adapters/basic.py", line 255, in _write_property
    self._set_property(val_prop, *args)
  File "/home/cavada/Projects/pygtkmvc/trunk.157/gtkmvco/gtkmvc/adapters/basic.py", line 232, in _set_property
    return setattr(self._model, self._prop_name, val)
  File "<string>", line 6, in set_prop_text
  File "/home/cavada/Projects/pygtkmvc/trunk.157/gtkmvco/gtkmvc/model.py", line 381, in notify_property_value_change
    self, old, new) # notifies the change
  File "/home/cavada/Projects/pygtkmvc/trunk.157/gtkmvco/gtkmvc/model.py", line 367, in __notify_observer__
    return method(*args, **kwargs)
  File "/home/cavada/Projects/pygtkmvc/trunk.157/gtkmvco/gtkmvc/adapters/basic.py", line 220, in _observer_fun
    self._on_prop_changed()
TypeError: _on_prop_changed() takes exactly 6 arguments (1 given)